spring.mongodb.uri=${MONGODB_URI:mongodb://127.0.0.1:27017/smartcampusdb?serverSelectionTimeoutMS=1000&connectTimeoutMS=1000&socketTimeoutMS=1000}
spring.mongodb.database=${MONGODB_DATABASE:smartcampusdb}
spring.data.mongodb.uri=${spring.mongodb.uri}
spring.data.mongodb.database=${spring.mongodb.database}
server.port=8081
